PanorbitBackendAssignment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('account.urls')),
    path("api/", include('api.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
    path("", views.dashboard,name="dashboard"),
    path("signup", views.signup, name="signup"),
    path("login", views.logins, name="login"),
    path("logout", views.logouts, name="logout"),
    path("otp_verify/<str:mobile>", views.otp_verify, name="otp_verify"),
    path("re_send_otp/<str:mobile>", views.re_send_otp, name="re_send_otp"),
    path("autosuggest/", views.autosuggest, name="autosuggest"),
    path("display", views.display, name="display"),
    path("country_details/<str:code>", views.country_details, name="country_details"),
]

api/urls.py
from django.urls import path
from api import views

app_name = 'api'
urlpatterns = [
    path("signup", views.signup, name="signup"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("otp_verify/<str:mobile>", views.otp_verify, name="otp_verify"),
    path("re_send_otp/<str:mobile>", views.re_send_otp, name="re_send_otp"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body class="bg-light">
<nav class="navbar navbar-expand-lg bg-light shadow-sm sticky-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'account:dashboard' %}">World</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'account:dashboard' %}">Home</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <p class="nav-link fw-bold">{{ request.user.first_name }} {{ request.user.last_name }}</p>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:signup' %}">Signup</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container mt-3">
    <div class="row">
        {% block content %}{% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $(".form-group>input,select,textarea").addClass("form-control");
    });

</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>
</html>

templates/country_details.html
{% extends 'base.html' %}
{% block content %}
    <div class="col-lg-12">
        <div class="row mb-2">
            <div class="col-lg-10 mx-auto">
                <div class="card">
                    <div class="card-body">
                        <h5 class="text-center text-decoration-underline">Country</h5>
                        <p class="fw-bold">Name: <span class="fw-normal">{{ country.name }}</span></p>
                        <p class="fw-bold">Code: <span class="fw-normal">{{ country.code }}</span></p>
                        <p class="fw-bold">Continent: <span class="fw-normal">{{ country.continent }}</span></p>
                        <p class="fw-bold">Population: <span class="fw-normal">{{ country.population }}</span></p>
                        <p class="fw-bold">Local Name: <span class="fw-normal">{{ country.localname }}</span></p>
                        <p class="fw-bold">Surface Area: <span class="fw-normal">{{ country.surfacearea }}</span></p>
                        <p class="fw-bold">Capital: <span class="fw-normal">{{ country.capital }}</span></p>
                        <p class="fw-bold">Region: <span class="fw-normal">{{ country.region }}</span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="col-lg-6 mx-auto">
        <div class="card shadow-sm">
            <div class="card-body p-5">
                <h1 class="text-center">Dashboard</h1>
                <form action="{% url 'account:display' %}" method="GET">
                    <div class="searchInput">
                        <input type="text" name="search" id="search" class="form-control form-control-lg shadow-sm"
                               placeholder="Search by city, country, or language">
                        <div class="list-group list-group-flush shadow-sm" id="autosuggest-results" style="z-index: 10;position: absolute;width: 85%"></div>
                    </div>
                    <div class="d-grid gap-2 col-4 mx-auto mt-4">
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="{% static 'autosuggest.js' %}"></script>
{% endblock %}

templates/display.html
{% extends 'base.html' %}
{% load template_tags %}
{% block content %}
    <div class="col-lg-12">
        {% for result in page_obj %}
            {% if result|model_name == 'city' %}
                <div class="row mb-2">
                    <div class="col-lg-10 mx-auto">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="text-center text-decoration-underline">City</h5>
                                <p class="fw-bold">Name: <span class="fw-normal">{{ result.name }}</span></p>
                                <p class="fw-bold">District: <span class="fw-normal">{{ result.district }}</span></p>
                                <p class="fw-bold">Population: <span class="fw-normal">{{ result.population }}</span></p>
                                <p class="fw-bold">Country: <span class="fw-normal">{{ result.countrycode.name }}</span></p>
                            </div>
                        </div>
                    </div>
                </div>
            {% elif result|model_name == 'country' %}
                <div class="row mb-2">
                    <div class="col-lg-10 mx-auto">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="text-center text-decoration-underline">Country</h5>
                                <p class="fw-bold">Name: <span class="fw-normal">{{ result.name }}</span></p>
                                <p class="fw-bold">Code: <span class="fw-normal">{{ result.code }}</span></p>
                                <p class="fw-bold">Continent: <span class="fw-normal">{{ result.continent }}</span></p>
                                <p class="fw-bold">Population: <span class="fw-normal">{{ result.population }}</span></p>
                                <p class="fw-bold">Local Name: <span class="fw-normal">{{ result.localname }}</span></p>
                                <p class="fw-bold">Surface Area: <span class="fw-normal">{{ result.surfacearea }}</span></p>
                                <p class="fw-bold">Capital: <span class="fw-normal">{{ result.capital }}</span></p>
                                <p class="fw-bold">Region: <span class="fw-normal">{{ result.region }}</span></p>
                            </div>
                        </div>
                    </div>
                </div>
            {% elif result|model_name == 'countrylanguage' %}
                <div class="row mb-2">
                    <div class="col-lg-10 mx-auto">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="text-center text-decoration-underline">Country Language</h5>
                                <p class="fw-bold">Language: <span class="fw-normal">{{ result.language }}</span></p>
                                <p class="fw-bold">Country: <span class="fw-normal">{{ result.countrycode.name }}</span></p>
                                <p class="fw-bold">Percentage: <span class="fw-normal">{{ result.percentage }}</span></p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% empty %}
            <p class="text-danger fw-bold">No result found!.</p>
        {% endfor %}
    <!-- pagination start -->
    {% if count > 0 %}
    <nav aria-label="Page navigation example " style="margin-top: 10px!important;">
    <div class="row">
            <ul class="small">Showing <b>{{ page_obj.number }}</b> / <b>{{ page_obj.paginator.num_pages }}</b> entries</ul>
            <ul class="pagination pagination-sm ml-auto mr-4">
                  {% if page_obj.has_previous %}
                    <li class="page-item ">
                        <a href="?search={{ search }}&page={{ page_obj.previous_page_number }}" class="page-link"><i class="fas fa-long-arrow-alt-left  text-muted"> Previous</i></a>
                    </li>
                  {% else %}
                      <li class="page-item disabled mr-2">
                        <i class="fas fa-long-arrow-alt-left  page-link text-muted"> Previous</i>
                    </li>
                  {% endif %}
                  {% if page_obj.paginator.num_pages == 1 %}
                      <li class="page-item active"><a href="#" class="page-link">{{ page_obj.number }}</a></li>
                  {% elif page_obj.number == 1 %}
                      <li class="page-item active"><a href="#" class="page-link">{{ page_obj.number }}</a></li>
                      <li class="page-item "><a href="?search={{ search }}&page={{ page_obj.number|add:1 }}" class="page-link">{{ page_obj.number|add:1 }}</a></li>
                      <li class="page-item "><a href="?search={{ search }}&page={{ page_obj.paginator.num_pages }}" class="page-link">{{ page_obj.paginator.num_pages }}</a></li>
                  {% elif page_obj.number|add:-1 == 1 %}
                      <li class="page-item "><a href="?search={{ search }}&page=1" class="page-link">1</a></li>
                      <li class="page-item active"><a href="#" class="page-link">{{ page_obj.number }}</a></li>
                      <li class="page-item "><a href="?search={{ search }}&page={{ page_obj.number|add:1 }}" class="page-link">{{ page_obj.number|add:1 }}</a></li>
                      <li class="page-item "><a href="?search={{ search }}&page={{ page_obj.paginator.num_pages }}" class="page-link">{{ page_obj.paginator.num_pages }}</a></li>
                  {% elif page_obj.number == page_obj.paginator.num_pages %}
                      <li class="page-item "><a href="?search={{ search }}&page=1" class="page-link">1</a></li>
                      <li class="page-item "><a href="?search={{ search }}&page={{ page_obj.number|add:-1 }}" class="page-link">{{ page_obj.number|add:-1 }}</a></li>
                      <li class="page-item active"><a href="#" class="page-link">{{ page_obj.number }}</a></li>
                  {% elif page_obj.number|add:1 == page_obj.paginator.num_pages %}
                      <li class="page-item "><a href="?search={{ search }}&page=1" class="page-link">1</a></li>
                      <li class="page-item "><a href="?search={{ search }}&page={{ page_obj.number|add:-1 }}" class="page-link">{{ page_obj.number|add:-1 }}</a></li>
                      <li class="page-item active"><a href="#" class="page-link">{{ page_obj.number }}</a></li>
                      <li class="page-item "><a href="?search={{ search }}&page={{ page_obj.paginator.num_pages }}" class="page-link">{{ page_obj.paginator.num_pages }}</a></li>
                  {% else %}
                      <li class="page-item "><a href="?search={{ search }}&page=1" class="page-link">1</a></li>
                      <li class="page-item "><a href="?search={{ search }}&page={{ page_obj.number|add:-1 }}" class="page-link">{{ page_obj.number|add:-1 }}</a></li>
                      <li class="page-item active"><a href="#" class="page-link">{{ page_obj.number }}</a></li>
                      <li class="page-item "><a href="?search={{ search }}&page={{ page_obj.number|add:1 }}" class="page-link">{{ page_obj.number|add:1 }}</a></li>
                      <li class="page-item "><a href="?search={{ search }}&page={{ page_obj.paginator.num_pages }}" class="page-link">{{ page_obj.paginator.num_pages }}</a></li>
                  {% endif %}

                  {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="?search={{ search }}&page={{ page_obj.next_page_number }}" class="page-link"><i class="fas fa-long-arrow-alt-right  text-muted"> Next</i></a>
                    </li>
                  {% else %}
                      <li class="page-item disabled ml-2">
                        <i class="fas fa-long-arrow-alt-right page-link  text-muted"> Next</i>
                    </li>
                  {% endif %}

                </ul>
    </div>
        </nav>
    {% endif %}
    <!-- pagination end -->
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="col-lg-6 mx-auto ">
        <div class="card shadow">
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {% for foo in messages %}
                        <div class="alert {{ foo.tags }}  alert-dismissible fade show " role="alert">
                            {{ foo }}
                            <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                    {% for f in form %}
                        <div class="form-group">
                            {{ f.label_tag }}
                            {{ f }}
                            <label for="" class="text-danger">{{ f.errors }}</label>
                        </div>
                    {% endfor %}

                    <input type="submit" value="Login" class="btn btn-block btn-info text-light">
                </form>
                <a href="{% url 'account:signup' %}" class="mt-2">Register</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/otp_verify.html
{% extends 'base.html' %}
{% block content %}
    <div class="col-lg-6 mx-auto">
        <div class="card shadow">
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {% for foo in messages %}
                        <div class="alert {{ foo.tags }}  alert-dismissible fade show " role="alert">
                            {{ foo }}
                            <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                    {% for f in form %}
                        <div class="form-group">
                            {{ f.label_tag }}
                            {{ f }}
                            <label for="" class="text-danger">{{ f.errors }}</label>
                        </div>
                    {% endfor %}
                    <input type="submit" value="Verify" class="btn btn-block btn-info text-light">
                </form>
                <a href="{% url 'account:re_send_otp' mobile %}" class="btn btn-primary mt-2">Re-Send OTP</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% block content %}
    <div class="col-lg-6 mx-auto ">
        <div class="card shadow">
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {% for foo in messages %}
                        <div class="alert {{ foo.tags }}  alert-dismissible fade show " role="alert">
                            {{ foo }}
                            <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                    {% for f in form %}
                        <div class="form-group">
                            {{ f.label_tag }}
                            {{ f }}
                            <label for="" class="text-danger">{{ f.errors }}</label>
                        </div>
                    {% endfor %}

                    <input type="submit" value="Signup" class="btn btn-block btn-info text-light">
                </form>
                <a href="{% url 'account:login' %}" class="mt-2">Login</a>
            </div>
        </div>
    </div>
{% endblock %}